version: '2.1'
services:
  api-gateway:
    image: api-gateway
    build:
      context: .
      dockerfile: test.Dockerfile
    environment:
      GW_AUTH_URL: 'http://localhost:8084/auth/login'
      GW_DOCS_URL: 'http://localhost:3000/api/files'
      GW_PORT: 8080
      GW_UPLOAD_SERVICE: 'upload-service:8080'
      GW_DOWNLOAD_SERVICE: 'download-service:8080'
      GW_FILE_SERVICE: 'file-service:8080'
      GW_PERMISSION_SERVICE: 'permission-service:8080'
      GW_EXTERNAL_APM_URL: http://localhost:8200
      GW_ALLOW_ORIGINS: http://localhost*
      GW_SUPPORT_LINK: "https://open.rocket.chat"
      GW_CHROME_DOWNLOAD_URL: "https://google.com/chrome/"
      ELASTICSEARCH_URL: http://localhost:9200
      LOG_INDEX: kdrive
      LOG_LEVEL: info
      ELASTIC_APM_SERVER_URL: http://localhost:8200
      ELASTIC_APM_SERVICE_NAME: api-gateway
      ELASTIC_APM_SERVICE_VERSION: 0.1
      ELASTIC_APM_ENVIRONMENT: development
      ELASTIC_APM_ACTIVE: 'true'
      ELASTIC_APM_IGNORE_URLS: /api/healthcheck
      ELASTIC_APM_CAPTURE_BODY: 'off'
      ELASTIC_APM_METRICS_INTERVAL: 10s
      GW_SECRET: pandora@drive
    ports:
      - '8080:8080'
    depends_on:
      - upload-service
      - download-service
      - file-service
      - authentication-service
      - permission-service
      - search-service
  minio:
    image: minio/minio
    volumes:
      - './data:/data'
    ports:
      - '9000:9000'
    environment:
      MINIO_ACCESS_KEY: 'F6WUUG27HBUFSIXVZL59'
      MINIO_SECRET_KEY: 'BPlIUU6SX0ZxiCMo3tIpCMAUdnmkN9Eo9K42NsRR'
    command: server /data
  upload-service:
    image: 'drivehub.azurecr.io/meateam/upload-service:v2.0.0'
    environment:
      S3_ACCESS_KEY: F6WUUG27HBUFSIXVZL59
      S3_SECRET_KEY: BPlIUU6SX0ZxiCMo3tIpCMAUdnmkN9Eo9K42NsRR
      S3_ENDPOINT: 'http://minio:9000'
      TCP_PORT: 8080
      HOST_NAME: upload-service
      ELASTICSEARCH_URL: http://localhost:9200
      LOG_INDEX: kdrive
      LOG_LEVEL: debug
      ELASTIC_APM_SERVER_URL: 'http://localhost:8200'
      ELASTIC_APM_SERVICE_NAME: 'upload-service'
      ELASTIC_APM_SERVICE_VERSION: '0.1'
      ELASTIC_APM_ENVIRONMENT: 'development'
      ELASTIC_APM_ACTIVE: 'true'
      ELASTIC_APM_CAPTURE_BODY: 'off'
      ELASTIC_APM_METRICS_INTERVAL: '10s'
    depends_on:
      - minio
    ports:
      - '8081:8080'
  download-service:
    image: 'drivehub.azurecr.io/meateam/download-service:v2.0.0'
    environment:
      S3_ACCESS_KEY: F6WUUG27HBUFSIXVZL59
      S3_SECRET_KEY: BPlIUU6SX0ZxiCMo3tIpCMAUdnmkN9Eo9K42NsRR
      S3_ENDPOINT: 'http://minio:9000'
      TCP_PORT: 8080
      HOST_NAME: download-service
      ELASTICSEARCH_URL: http://localhost:9200
      LOG_INDEX: kdrive
      LOG_LEVEL: debug
      ELASTIC_APM_SERVER_URL: 'http://localhost:8200'
      ELASTIC_APM_SERVICE_NAME: 'download-service'
      ELASTIC_APM_SERVICE_VERSION: '0.1'
      ELASTIC_APM_ENVIRONMENT: 'development'
      ELASTIC_APM_ACTIVE: 'true'
      ELASTIC_APM_CAPTURE_BODY: 'off'
      ELASTIC_APM_METRICS_INTERVAL: '10s'
    ports:
      - '8082:8080'
    depends_on:
      - minio
  file-service:
    image: 'drivehub.azurecr.io/meateam/file-service:v2.0.0'
    environment: 
      MONGO_HOST: mongodb://mongo:27017/devDB
    ports:
      - '8083:8080'
    depends_on:
      - mongo
  mongo:
    image: 'mongo:4.0.9'
    ports:
      - '27017:27017'
    volumes:
      - './data/db:/data/db'
    depends_on:
      - minio
  authentication-service:
    image: 'drivehub.azurecr.io/meateam/authentication-service:v2.0.0'
    ports:
      - '8084:8080'
    environment: 
      SAML_ENTRY_POINT: 'http://localhost:8085/simplesaml/saml2/idp/SSOService.php'
      SAML_ISSUER: 'http://localhost:8084/auth/metadata.xml'
      SAML_CALLBACK_URL: 'http://localhost:8084/auth/metadata.xml/callback'
      USERS_RPC_ENDPOINT: 'user-service:8080'
      SECRET_KEY: pandora@drive
      CLIENT_ENDPOINT: 'http://localhost:8080/api/config'
      STRATEGY: 'saml'
    depends_on:
      - user-service
  user-service:
    image: 'drivehub.azurecr.io/meateam/user-service:v2.0.0'
    ports:
      - '8086:8080'
    environment:
      KARTOFFEL_URL: http://localhost:8080
      RPC_PORT: 8080
    depends_on:
      - mongo
      - redis
  permission-service:
    image: 'drivehub.azurecr.io/meateam/permission-service:v2.0.0'
    ports:
      - '8087:8080'
    environment:
      PORT: 8080
      HOST_NAME: permission-service
      MONGO_HOST: mongodb://mongo:27017/permission
      ELASTICSEARCH_URL: http://localhost:9200
      LOG_INDEX: kdrive
      LOG_LEVEL: debug
      HEALTH_CHECK_INTERVAL: 5
      ELASTIC_APM_SERVER_URL: 'http://localhost:8200'
      ELASTIC_APM_SERVICE_NAME: 'permission-service'
      ELASTIC_APM_SERVICE_VERSION: '0.1'
      ELASTIC_APM_ENVIRONMENT: 'development'
      ELASTIC_APM_ACTIVE: 'true'
      ELASTIC_APM_CAPTURE_BODY: 'all'
      ELASTIC_APM_METRICS_INTERVAL: '10s'
      ELASTIC_APM_IGNORE_URLS: '/grpc.health.v1.Health/Check'
    depends_on:
      - mongo
  search-service:
    image: drivehub.azurecr.io/meateam/search-service:v2.0.0
    environment:
      ELASTICSEARCH_URL: http://localhost:9200
      LOG_INDEX: kdrive
      LOG_LEVEL: info
      ELASTIC_APM_SERVER_URL: http://localhost:8200
      ELASTIC_APM_SERVICE_NAME: api-gateway
      ELASTIC_APM_SERVICE_VERSION: 0.1
      ELASTIC_APM_ENVIRONMENT: development
      ELASTIC_APM_ACTIVE: 'true'
      ELASTIC_APM_IGNORE_URLS: /api/healthcheck
      ELASTIC_APM_CAPTURE_BODY: 'off'
      ELASTIC_APM_METRICS_INTERVAL: 10s
      GW_SECRET: pandora@drive
    ports:
      - 8088:8080
    depends_on: 
      elasticsearch:
        condition: service_healthy
  spike-service:
    image: drivehub.azurecr.io/meateam/spike-service:v2.0.0
    environment:
        ELASTICSEARCH_URL: http://localhost:9200
        LOG_INDEX: kdrive
        LOG_LEVEL: info
        ELASTIC_APM_SERVER_URL: http://localhost:8200
        ELASTIC_APM_SERVICE_NAME: api-gateway
        ELASTIC_APM_SERVICE_VERSION: 0.1
        ELASTIC_APM_ENVIRONMENT: development
        ELASTIC_APM_ACTIVE: 'true'
        ELASTIC_APM_IGNORE_URLS: /api/healthcheck
        ELASTIC_APM_CAPTURE_BODY: 'off'
        ELASTIC_APM_METRICS_INTERVAL: 10s
        GW_SECRET: pandora@drive
    depends_on:
      - redis
    ports:
      - '8090:8080'
  delegation-service:
    image: drivehub.azurecr.io/meateam/delegation-service:v2.0.0
    ports:
      - '8091:8080'
    environment:
      ELASTICSEARCH_URL: http://localhost:9200
      LOG_INDEX: kdrive
      LOG_LEVEL: info
      ELASTIC_APM_SERVER_URL: http://localhost:8200
      ELASTIC_APM_SERVICE_NAME: api-gateway
      ELASTIC_APM_SERVICE_VERSION: 0.1
      ELASTIC_APM_ENVIRONMENT: development
      ELASTIC_APM_ACTIVE: 'true'
      ELASTIC_APM_IGNORE_URLS: /api/healthcheck
      ELASTIC_APM_CAPTURE_BODY: 'off'
      ELASTIC_APM_METRICS_INTERVAL: 10s
      GW_SECRET: pandora@drive
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    environment: 
      - discovery.type=single-node
    container_name: elasticsearch
    ports: ['9200:9200']
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 5s
      timeout: 10s
      retries: 5
